=== Rodez-IUT/dut-info2-filmprovider-tanguyfenouillot/Part1-XML-DTD/resources/XML3/Librairie.dtd
<!ENTITY % personne "nom,prenom?">
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT prenom (#PCDATA)>

<!ENTITY copyright "&#xA9;Librairie &amp; Internet 2020">

<!ENTITY % texteHTML "#PCDATA|strong|em|img">
        <!ELEMENT strong (#PCDATA)>
        <!ELEMENT em (#PCDATA)>
        <!ELEMENT img EMPTY>
        <!ATTLIST img src CDATA #REQUIRED
                title CDATA #IMPLIED
                >

<!ELEMENT description (%texteHTML;)*>

<!ELEMENT prix (#PCDATA)>
    <!ATTLIST prix devise (euro|livre|dollar) "euro"
                   type (HT|TTC) "HT"
                   tva CDATA #FIXED "5.5"
    >

<!ELEMENT titre (#PCDATA)>

<!ELEMENT auteur ((%personne;)*|collectif)>
    <!ELEMENT collectif (direction,membres)>
    <!ELEMENT direction (%personne;)>
    <!ELEMENT membres (#PCDATA)>

<!ELEMENT livre (titre, auteur+, description, prix)>
    <!ATTLIST livre numISBN NMTOKENS #REQUIRED>

<!ELEMENT librairie (entete, livre+)>

<!ELEMENT entete (%texteHTML;)*>

=== Rodez-IUT/dut-info2-filmprovider-tanguyfenouillot/Part1-XML-DTD/resources/XML3/Librairie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE librairie SYSTEM "Librairie.dtd">
<librairie>
    <entete>
        <strong>Librairie de Rodez</strong>
        &copyright;
    </entete>
    <livre numISBN="9791035805319">
        <titre>Les Fleurs du mal</titre>
        <auteur>
            <nom>Baudelaire</nom>
            <prenom>Charles</prenom>
        </auteur>
        <description>
            Les Fleurs du mal est un recueil
            de poèmes de Charles Baudelaire, englobant la
            quasi-totalité de sa production en vers, de 1840
            jusqu'à sa mort survenue fin août 1867.
        </description>
        <prix devise="euro">20</prix>
    </livre>
</librairie>
